export const scraperConfig = {
  archiveUrl: "https://www.theverge.com/installer-newsletter",
  baseUrl: "https://www.theverge.com",
  delayBetweenRequests: 2000,
  maxRetries: 3,
  timeout: 30000,
  headless: true,
  userAgent:
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
};

export const SKIP_URL_PATTERNS = [
  /theverge\.com\/ethics/,
  /theverge\.com\/privacy/,
  /theverge\.com\/terms/,
  /theverge\.com\/contact/,
  /theverge\.com\/about/,
  /theverge\.com\/sitemap/,
  /theverge\.com\/rss/,
  /theverge\.com\/authors\//,
  /theverge\.com\/installer-newsletter\/?$/,
  /theverge\.com\/installer-newsletter\/archives/,
  /theverge\.com\/pages\//,
  /theverge\.com\/?$/,
  /twitter\.com\/intent/,
  /twitter\.com\/verge/,
  /facebook\.com\/sharer/,
  /linkedin\.com\/share/,
  /instagram\.com\/verge/,
  /threads\.net\/.*verge/,
  /tiktok\.com\/@verge/,
  /voxmedia\.com/,
  /onetrust\.com/,
  /status\.voxmedia/,
  /mailto:/,
  /#comments/,
  /^#/,
  /\.(css|js|woff|png|jpg|ico|svg)$/,
];

export const JUNK_TITLE_PATTERNS = [
  /^see all/i,
  /^comments?\s*\d*/i,
  /^\d+\s*comments?/i,
  /^share$/i,
  /^icon/i,
  /^subscribe/i,
  /^sign up/i,
  /^read more$/i,
  /^click here/i,
  /^here$/i,
  /^link$/i,
  /^\d+$/,
  /^the$/i,
  /^a$/i,
  /^an$/i,
  /^\s*$/,
];
